config/routes.rb
HyperAlerts::Application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root to: "home#index"

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    post :migrate, on: :member
    get :time_zone_difference, on: :member
  end

  resources :subscriptions

  get "help/" => "help#index"
  get "statistics/summary" => "statistics#summary"

  # Preview e-mails in development
  if Rails.env.development?
    mount UserMailerPreview => "user_mailer_preview"
    mount SubscriptionMailerPreview => "subscription_mailer_preview"
  end

  # Non-idempotent GET request to destroy subscriptions upon clicking a link in the e-mail
  get "subscriptions/:id/destroy" => "subscriptions#destroy", as: "destroy_subscription"

  # Non-idempotent GET request to destroy users upon clicking a link in the e-mail
  get "users/:id/destroy" => "users#destroy", as: "destroy_user"

  namespace :services do
    namespace :twitter do
      resource :users do
        get "search" => "users#search"
      end
    end
    namespace :facebook do
      get "realtime", to: "real_time#verify"
      post "realtime", to: "real_time#push"
    end
  end

  resources :notifications do
    post :email, on: :collection
  end

  match "/404", to: "errors#not_found"
  match "/500", to: "errors#internal_server_error"
end

app/models/services/facebook/user.rb
class Services::Facebook::User
  include Mongoid::Document

  # A String describing the Facebook user's name.
  field :name, type: String

  embedded_in :authorable, polymorphic: true

  # Returns a String describing the URL to the user's profile.
  def profile_url
    "https://facebook.com/#{id}"
  end

  # Returns a String describing the URL to the user's picture.
  def picture_url
    "https://graph.facebook.com/#{id}/picture"
  end
end

app/models/services/twitter/user.rb
class Services::Twitter::User
  include Mongoid::Document

  # A number describing the Twitter ID of the user
  field :twitter_id

  # A string describing the Twitter user's name.
  field :name, type: String

  # A string describing the url for the Twitter user's profile image.
  field :picture_url, type: String

  # A string describing the Twitter users's screen name
  field :screen_name, type: String

  embedded_in :authorable, polymorphic: true

  validates :twitter_id, presence: true
  validates :screen_name, presence: true
end

app/models/user.rb
class User
  include Mongoid::Document

  devise :confirmable, :trackable, :omniauthable, :token_authenticatable

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  # Confirmable
  field :confirmation_token,   type: String
  field :confirmed_at,         type: Time
  field :confirmation_sent_at, type: Time
  field :unconfirmed_email,    type: String

  # Omniauthable
  field :provider, type: String
  field :uid, type: String

  ## Token authenticatable
  field :authentication_token, type: String

  before_save :ensure_authentication_token

  # A String describing the user's name.
  field :name, type: String

  # A String describing the user's e-mail address.
  field :email, type: String

  # A String describing the user's secret token from Hyper Alerts 1.
  field :legacy_id, type: String

  # A String describing the name of the user's time zone.
  field :time_zone_name, type: String, default: "UTC"

  # A Time instance describing when the user's e-mail address started bouncing.
  field :bouncing_since, type: Time

  # A Services::Facebook::AccessToken instance.
  has_one :facebook_access_token, class_name: "Services::Facebook::AccessToken"

  # A Services::Twitter::AcessToken instance.
  has_one :twitter_access_token, class_name: "Services::Twitter::AccessToken"

  # An Invitation instance.
  has_one :invitation

  # A collection of Subscription instances.
  has_many :subscriptions, dependent: :destroy do
    def facebook
      where subscribable_type: "Services::Facebook::Page"
    end

    def twitter_search
      where subscribable_type: "Services::Twitter::Search"
    end

    def twitter_timeline
      where subscribable_type: "Services::Twitter::Timeline"
    end
  end

  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, allow_blank: true }

  before_save do |user|
    user.bouncing_since = nil if user.email_changed?
  end

  # Determine whether the user subscribes to the given subscribable.
  #
  # subscirbable - An instance of a subscribable model.
  def subscribes_to? subscribable
    subscriptions.any? do |subscription|
      subscription.subscribable == subscribable
    end
  end

  # Query Facebook for the user.
  #
  # * options - A Hash of options:
  #             :lazy - A Boolean describing whether to defer the query to Facebook.
  #
  # Returns a FbGraph::User instance.
  def graph options = {}
    user = FbGraph::User.new "me", access_token: facebook_access_token.token

    unless options[:lazy]
      user.fetch
    else
      user
    end
  end

  def time_zone
    ActiveSupport::TimeZone.new time_zone_name
  end

  # Determine whether the user's e-mails are bouncing.
  #
  # Returns a Boolean.
  def bouncing?
    !!bouncing_since
  end

  def to_s
    email
  end
end

app/controllers/services/twitter/users_controller.rb
class Services::Twitter::UsersController < ApplicationController
  respond_to :json

  # Proxy for Twitter search API endpoint
  def search
    token = current_user.twitter_access_token
    client = Twitter::Client.new oauth_token: token.token, oauth_token_secret: token.secret

    @users = client.user_search params['q'], {
      count: params['count']
    }

    respond_with @users
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_filter :authenticate_user!, only: [:twitter]

  # Create and/or sign in a Facebook user.
  def facebook
    user = User.find_or_initialize_by provider: auth.provider, uid: auth.uid do |user|
      # We don't get an e-mail address from Facebook, so we can't very well confirm it.
      user.skip_confirmation!
    end

    if user.new_record?
      token = Services::Facebook::AccessToken.new do |token|
        token.user       = user
        token.token      = auth.credentials.token

        if auth.credentials.expires_at.nil?
          token.expires_at = nil
        else
          token.expires_at = Time.at auth.credentials.expires_at
        end
      end

      user.name = user.graph.name

      user.save
      token.save
    else
      user.facebook_access_token.renew auth.credentials.token, auth.credentials.expires_at
    end

    sign_in_and_redirect user, event: :authentication
  end

  # Authorize with Twitter and store the access token on the user
  def twitter
    user = current_user

    if user.twitter_access_token.present?
      user.twitter_access_token.renew auth.credentials.token, auth.credentials.secret
    else
      token = Services::Twitter::AccessToken.new do |token|
        token.user    = user
        token.token   = auth.credentials.token
        token.secret  = auth.credentials.secret
      end

      token.save!
    end

    redirect_to subscriptions_url
  end

  private

  def auth
    request.env["omniauth.auth"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_user
  before_filter :require_self, only: [:edit, :update, :time_zone_difference, :destroy]

  def edit
    respond_to do |format|
      format.html
    end
  end

  def update
    respond_to do |format|
      @user.email          = params[:user][:email]
      @user.time_zone_name = params[:user][:time_zone_name]

      @user.skip_reconfirmation! if params[:user][:email].blank?

      if @user.save
        format.html { redirect_to edit_user_url(@user), notice: "Settings updated" }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @user.destroy

    redirect_to :root
  end

  def migrate
    legacy = Legacy.new params[:email], params[:password]

    respond_to do |format|

      begin
        subscriptions = legacy.subscriptions
      rescue Legacy::Error => error
        format.html { redirect_to :back, alert: error.message }
      else
        subscriptions.map do |subscription|
          # Ignore pages that the user already subscribes to.
          next if current_user.subscribes_to? subscription.subscribable

          subscription.user = current_user
          subscription.save!
        end

        legacy.disable

        @subscriptions = subscriptions

        format.html
      end
    end
  end

  def time_zone_difference
    time_zone_name = params[:time_zone_name]

    current_time_zone = ActiveSupport::TimeZone[time_zone_name]

    if current_time_zone
      difference_in_hours = (current_time_zone.utc_offset - @user.time_zone.utc_offset) / 60 / 60

      render text: difference_in_hours
    else
      render text: "Unsupported time zone", status: :bad_request
    end
  end

  private

  def get_user
    id = params[:id]

    if id == "me"
      @user = current_user
    else
      @user = User.find params[:id]
    end
  end

  def require_self
    unless @user == current_user
      render text: "Forbidden", status: :forbidden
    end
  end
end

app/helpers/services/twitter/users_helper.rb
module Services::Twitter::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def facebook_permissions
    current_user.graph.permissions
  end
end

app/views/users/edit/_general.html.erb
<div class="settings general" id="general">
  <header class="header">
    <h1>General settings</h1>
  </header>

  <div class="body">
    <% if @user.errors.any? %>
      <ul class="errors">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    <% end %>

    <%= form_for @user do |form| %>

    <div class="field" id="email">
      <%= form.label :email %>
      <%= form.email_field :email %>

      <% if @user.unconfirmed_email.present? %>
        <p class="note">
          Your e-mail address has been changed to <strong><%= @user.unconfirmed_email %></strong>, but you need
          to confirm that it's yours before we can accept it.
        </p>
      <% end %>
    </div>

    <div class="field" id="time_zone">
      <%= form.label :time_zone %>
      <%= form.time_zone_select :time_zone_name %>
    </div>

    <%= submit_tag "Save" %>

    <% end %>

  </div>

</div>

app/views/users/edit/_import_alerts.html.erb
<div class="settings import-alerts" id="import-alerts">
  <header class="header">
    <h1>Import alerts from old Hyper Alerts</h1>
  </header>

  <div class="body">
    <p>
      If you already have a user account on the old version of Hyper Alerts you can use this form to import
      all your subscriptions to Hyper Alerts 2.0.
    </p>

    <p>
      Enter the login credentials from the old Hyper Alerts to import:
    </p>

    <%= form_tag migrate_user_path, method: :post do %>
      <div class="field" id="email">
        <%= label_tag :email %>
        <%= text_field_tag :email %>
      </div>

      <div class="field" id="password">
        <%= label_tag :password %>
        <%= password_field_tag :password %>
      </div>

      <%= submit_tag "Import" %>
    <% end %>

  </div>

</div>

app/views/users/edit/_real_time_alerts.html.erb
<div class="settings real-time-alerts" id="real-time-alerts">
  <header class="header">
    <h1>Real-time alerts</h1>
  </header>

  <% if facebook_permissions.include? :manage_pages %>
    <div class="manage-pages-permissions-given body">
      <p class="field">
        You've already authorized us to manage your pages so we can alert you instantly. High five!
      </p>
    </div>
  <% else %>
    <div class="manage-pages-permissions-not-given body">
      <p class="field">
        Facebook says you have to authorize us to manage your pages if you want alerts
        instantly. But don't fret, we're not evil. Promise.
      </p>

      <a class="button" id="request-manage-pages-permissions" href="javascript://">Sure, no problem!</a>
    </div>
  <% end %>
</div>