config/routes.rb
HyperAlerts::Application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root to: "home#index"

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    post :migrate, on: :member
    get :time_zone_difference, on: :member
  end

  resources :subscriptions

  get "help/" => "help#index"
  get "statistics/summary" => "statistics#summary"

  # Preview e-mails in development
  if Rails.env.development?
    mount UserMailerPreview => "user_mailer_preview"
    mount SubscriptionMailerPreview => "subscription_mailer_preview"
  end

  # Non-idempotent GET request to destroy subscriptions upon clicking a link in the e-mail
  get "subscriptions/:id/destroy" => "subscriptions#destroy", as: "destroy_subscription"

  # Non-idempotent GET request to destroy users upon clicking a link in the e-mail
  get "users/:id/destroy" => "users#destroy", as: "destroy_user"

  namespace :services do
    namespace :twitter do
      resource :users do
        get "search" => "users#search"
      end
    end
    namespace :facebook do
      get "realtime", to: "real_time#verify"
      post "realtime", to: "real_time#push"
    end
  end

  resources :notifications do
    post :email, on: :collection
  end

  match "/404", to: "errors#not_found"
  match "/500", to: "errors#internal_server_error"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hyper Alerts</title>

    <script>
      USER_SIGNED_IN = <%= user_signed_in? %>;

      <% if user_signed_in? %>
        <% if current_user.facebook_access_token.present? %>
          FACEBOOK_ACCESS_TOKEN = "<%= current_user.facebook_access_token.token %>";
        <% else %>
          FACEBOOK_ACCESS_TOKEN = null;
        <% end %>

        <% if current_user.twitter_access_token.present? %>
          TWITTER_ACCESS_TOKEN = "<%= current_user.twitter_access_token.token %>";
        <% else %>
          TWITTER_ACCESS_TOKEN = null;
        <% end %>

        TWITTER_AUTH_URL = "<%= user_omniauth_authorize_path(:twitter) %>"
        USER_EMAIL = "<%= current_user.email %>";
      <% end %>
    </script>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js" %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!-- Nice and standardized meta tags -->
    <meta name="title" content="Hyper Alerts" />
    <meta name="description" content="Hyper Alerts is an easy to use email notification service for Facebook and Twitter. Subscribe to as many Facebook pages, Twitter accounts and search phrases as you like. Choose to get alerts within minutes, or a digest every hour, day, week or month. Sounds good, right?" />
    <meta name="Keywords" content="hyper alerts,hyper,alerts,notifications,subscriptions,alerts,email,alert,notify,facebook,twitter,free,trial,service,app"/> 
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

    <!-- Facebook and Open Graph shenanigans -->
    <meta property="og:title" content="Hyper Alerts" />
    <meta property="og:site_name" content="Hyper Alerts" />
    <meta property="og:type" content="product" />
    <meta property="og:url" content="http://www.hyperalerts.no"/>
    <meta property="og:video" content="http://vimeo.com/moogaloop.swf?clip_id=80799457&autoplay=1" />
    <meta property="og:video:width" content="398" />
    <meta property="og:video:height" content="224" />
    <meta property="og:video:type" content="application/x-shockwave-flash" />
    <meta property="og:description" content="Hyper Alerts is an easy to use email notification service for Facebook and Twitter. Subscribe to as many Facebook pages, Twitter accounts and search phrases as you like. Choose to get alerts within minutes, or a digest every hour, day, week or month. Sounds good, right?" />
    <meta property="fb:app_id" content="<%= Rails.application.config.facebook_application_id %>">

    <!-- Twitter tomfollery -->
    <meta name="twitter:title" value="Hyper Alerts">
    <meta name="twitter:site" value="@hyperoslo">
    <meta property="twitter:description" content="Hyper Alerts is an easy to use email notification service for Facebook and Twitter. Subscribe to as many Facebook pages, Twitter accounts and search phrases as you like. Choose to get alerts within minutes, or a digest every hour, day, week or month. Sounds good, right?" />      
    <meta name="twitter:card" value="player">
    <meta name="twitter:player" value="http://player.vimeo.com/video/80799457?title=0&amp;byline=0&amp;portrait=0">
    <meta property="twitter:player:width" content="398">
    <meta property="twitter:player:height" content="224">

    <!-- Sexy share images -->
    <link rel="image_src" href="<%= request.protocol %><%= request.host %>:<%= request.port %><%= image_path "share.png" %>"/>
    <meta property="og:image" content="<%= request.protocol %><%= request.host %>:<%= request.port %><%= image_path "share.png" %>"/>
    <meta name="twitter:image" value="<%= request.protocol %><%= request.host %>:<%= request.port %><%= image_path "share.png" %>">
  </head>

  <body class="<%= controller.controller_name %>">
    <div id="body">
      <%= render "shared/google_analytics" %>
      <%= render "shared/facebook_sdk" %>

      <% if user_signed_in? %>
      <header id="header">
        <div class="repository">
          <div class="logo"><a href="/"><%= image_tag "logo.png" %></a></div>
          <nav id="main-menu">
            <h2><%= link_to "Alerts", subscriptions_path, class: "subscriptions" %></h2>
            <h2><%= link_to "Settings", edit_user_path(current_user), class: "settings" %></h2>
            <h2><%= link_to "Help", help_path, class: "help" %></h2>
          </nav>
          <div class="account">
            <img src="http://graph.facebook.com/<%= current_user.uid %>/picture">
            <div class="details">
              <p><%= hello %>, <%= current_user.name %></p>
              <nav class="actions">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
              </nav>
            </div>
          </div>
        </div>
      </header>
      <% end %>

      <% if alert %>
      <div class="alert">
        <div class="repository">
          <%= alert %>
        </div>
      </div>
      <% end %>

      <% if notice %>
      <div class="notice">
        <div class="repository">
          <%= notice %>
        </div>
      </div>
      <% end %>

      <%= yield %>
    </div>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/layouts/statistics.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hyper Alerts</title>

    <%= stylesheet_link_tag    "statistics", :media => "all" %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js" %>
    <%= javascript_include_tag "statistics" %>
    <%= csrf_meta_tags %>

    <script>
      USER_SIGNED_IN = <%= user_signed_in? %>;
    </script>
  </head>

  <body class="statistics">
    <%= yield %>
  </body>
</html>

app/views/layouts/subscription_mailer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>HyperAlerts Email</title>
    <%= yield :head %>
  </head>

  <body>
    <table cellpadding="0" align="center" cellspacing="0" id="body">
      <tr id="logo">
        <td align="center">
          <%= image_tag "mailer/logo.png" %>
        </td>
      </tr>
      <tr id="header">
        <%= yield :header %>
      </tr>

      <%= yield %>

      <%= render :file => "/ads/index" if current_ad %>

      <tr>
        <td align="center" id="footer">
          <a href="http://hyperalerts.no" target="_blank">
            <%= image_tag "thanks_footer.png" %>
          </a>

          <p class="service_provider">
            Devised and crafted by <a href="http://hyper.no">Hyper</a> in Oslo, Norway.<br />
            If you have any questions, contact a viking at <a href="mailto:support@hyperalerts.no">support@hyperalerts.no</a>.
          </p>

          <p class="links">
            <%= link_to "Delete my subscription", destroy_subscription_url(@subscription, auth_token: @user.authentication_token) %>
            |
            <%= link_to "Delete my account", destroy_user_url(@user, auth_token: @user.authentication_token) %>
          </p>
        </td>
      </tr>

    </table>
  </body>
</html>